### ISSUE TITLE
Please add support for webp

### ISSUE THREAD

**Issue by yagamiyakumo** [Inareous/Minimal-CS-Manga-Reader#16]
As per title, thanks in advance!

**Comment by Inareous** [comment]
Try the v0.1.0.8 release.

I don't have any manga with webP, the only images i have as references are from google's [webP gallery](https://developers.google.com/speed/webp/gallery1).

Also, libwebp is divided by x86 and x64 OSes. I tested it only with x64 but I assume x86 would work just as well.

**Comment by yagamiyakumo** [comment]
Yup, it's working now. Will test more webp sources and update again if there's any issue. Thanks for the quick update! :)

**Comment by Inareous** [comment]
Closing for now.

Feel free to add if there's any problem and i'll reopen the issue.
