### ISSUE TITLE
Buttons misbehavior

### ISSUE THREAD

**Issue by ZIEXED** [Inareous/Minimal-CS-Manga-Reader#19]
1- On startup settings button is missing and doesn't appear until u press the themes switch button or entering then existing Fullscreen mode (disappear again after restarting the app)
2- After pressing the themes switch only half of the button is visible and stay like that until the app is restarted or entering then existing Fullscreen mode

![1](https://user-images.githubusercontent.com/14824755/87303731-271ce400-c503-11ea-9068-c2ea0ea3a57d.png)

![2](https://user-images.githubusercontent.com/14824755/87303754-300db580-c503-11ea-8dc4-151987d9c43f.png)

**Comment by Inareous** [comment]
This is unfortunately a problem with 3rd party tooling MaterialDesignInXaml and have been issued since 2017 ([#767](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/767)) without response.

I'll keep this up in case i found a manual fix.

**Comment by ZIEXED** [comment]
Won't forcing a redraw fix this?, or simply just resizing at startup the app width +1 then -1 again is enough and it won't be visible.
