### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by ZIEXED** [Inareous/Minimal-CS-Manga-Reader#2]
Feature request:
Keyboard shortcuts to
Next&Previous chapter
Switch Fullscreen mode (hopefully later)

**Comment by Inareous** [comment]
There is already keyboard shortcuts. These are the one you might want:

Next Chapter : Insert
Previous Chapter : Delete
Navigate Up & Down (1 screen) : Page Up & Down and Arrow Key Left & Right

Unfortunately currently there is no doc for the shortcut
