### ISSUE TITLE
Integrate with Explorer problem

### ISSUE THREAD

**Issue by ZIEXED** [Inareous/Minimal-CS-Manga-Reader#20]
After enabling Integration with Explorer and trying to open "Computer" or the user profile folder, Network, Recycle Bin, all result in opening the CS manga reader instead of Explorer.

**Comment by Inareous** [comment]
The current implementation registry key is placed for `Folder` extension while other newer program use `Directory` instead but I wouldn't count changing it will fix the problem. I can try making a separate release and have you try it first.

[withDirectoryRegistryContext x64.zip](https://github.com/Inareous/Minimal-CS-Manga-Reader/files/4915074/withDirectoryRegistryContext.x64.zip)
[withDirectoryRegistryContext x86.zip](https://github.com/Inareous/Minimal-CS-Manga-Reader/files/4915077/withDirectoryRegistryContext.x86.zip)

**Comment by ZIEXED** [comment]
Yup, I can confirm it's fixed.
