### ISSUE TITLE
Some chapters are out of order

### ISSUE THREAD

**Issue by Slasar41** [Inareous/Minimal-CS-Manga-Reader#23]
Some chapters are out of order, it's show just fine on DDS Manga Reader.
You can try reproduce it by downloading Tonikaku Cawaii from KissManga.
![image](https://user-images.githubusercontent.com/28888646/87823779-3eaaf280-c89e-11ea-95bb-bbea36a3ad23.png)
![image](https://user-images.githubusercontent.com/28888646/87823760-318e0380-c89e-11ea-9179-eb685da6cc4c.png)
Also, could you add application version number on titlebar?

**Comment by Slasar41** [comment]
Just noticed now I've two option in File Explorer context menu.
![image](https://user-images.githubusercontent.com/28888646/87824483-8d0cc100-c89f-11ea-9d89-01c9a0d1f9f1.png)
How to remove one?

**Comment by Inareous** [comment]
I re-uploaded v0.2.0 to include this fix, try re-downloading it again, it should fix the problem.

As for the registry, un-check and checking the context entry in the settings should work but in case it still doesn't, you can open regedit and navigate to `HKCU\Software\Classes\Folder\shell\` and remove `Minimal CS Manga Reader Context Menu` tree/folder

**Comment by Slasar41** [comment]
Okay, it's fixed. Thanks!
