### ISSUE TITLE
Read extracted chapters

### ISSUE THREAD

**Issue by ZIEXED** [Inareous/Minimal-CS-Manga-Reader#3]
~~Currently the application can't read extracted chapters (a folder with a non compressed images png jpg ect...)~~

Ok, seems like the problem was something else, trying to read the folder that contains the images directly fails but if I put the folder inside another folder it would work, is that's a bug that should be fixed or an intended behavior?
I suppose it needs to be fixed

**Comment by Inareous** [comment]
Good catch. This one probably will be fixed alongside feature of enabling opening chapter on the program
