### ISSUE TITLE
Chapter ordering option

### ISSUE THREAD

**Issue by NhKPaNdA** [Inareous/Minimal-CS-Manga-Reader#6]
Can you add an option in the settings to allow choosing between descending and ascending order for the chapters on load ?

**Comment by Inareous** [comment]
Could you elaborate on this?

**Comment by Slasar41** [comment]
Yeah, when I open the manga folder it jump to the last chapter.
I'd like an option to load from first chapter.

**Comment by NhKPaNdA** [comment]
As slasar said, if you load a folder with sub folders labeled 1 - 10 it will open in the "10" sub folder. An option to choose the reverse order, aka 10 - 1 instead, would be nice.
